const swaggerAutogen = require("swagger-autogen")();

// Import Swagger definitions if you have any predefined schemas (optional)
const swaggerDefinitions = require("./data/swaggerdefinitions.js"); // Adjust path if needed

const doc = {
  info: {
    version: "1.0.0",
    title: "Noroff E-Commerce",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000", // Update this with your host or production URL
  basePath: "/", // Base API path
  tags: [
    {
      name: "Brand",
      description: "Operations related to product brands",
    },
    {
      name: "Category",
      description: "Operations related to product categories",
    },
    {
      name: "Product",
      description: "Operations related to products",
    },
    {
      name: "Order",
      description: "Operations related to orders",
    },
    {
      name: "User",
      description: "Operations related to user management",
    },
    {
      name: "Cart",
      description: "Operations related to cart management",
    },
    {
      name: "Review",
      description: "Operations related to cart management",
    },
    {
      name: "Test",
      description:
        "Admin-specific operations, for testing with Jest. Use Backend routes for JSON responses.",
    },
  ],
  definitions: {
    ...swaggerDefinitions, // Include custom definitions if available
  },
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        in: "header",
        description:
          "JWT Authorization header using the Bearer scheme. Example: 'Authorization: Bearer {token}'",
        scheme: "bearer",
        bearerFormat: "JWT",
      },
    },
  },
  security: [
    {
      bearerAuth: [],
    },
  ],
};

const outputFile = "./swagger_output.json"; // Path for the generated Swagger JSON file
const endpointsFiles = [
  "./app.js", // Main entry point of your app
  "./controllers/BrandController.js", // Include specific controllers
  "./controllers/CategoryController.js",
  "./controllers/ProductController.js",
  "./controllers/OrderController.js",
  "./controllers/AuthController.js",
  "./controllers/CartController.js",
  // Add other controllers as necessary
];

// Generate the Swagger JSON and optionally start your app
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./bin/www"); // Replace with your server entry point if different
});
